[project]
name = "nn_verification_visualisation"

dynamic = ["version"]

dependencies = [
  "pyside6 >= 6.10.1",
  "onnx >= 1.20.1",
  "onnxruntime >= 1.23.0",
  "numpy >= 1.26.0",
  "matplotlib >= 3.10.8",
  "watchdog >= 6.0.0"
]

requires-python = ">=3.10"


description = ""
readme = "README.md"

authors = [
  {name = "Pradyun Gedam", email = "pradyun@example.com"},
  {name = "Tzu-Ping Chung", email = "tzu-ping@example.com"},
  {name = "Another person"},
  {email = "different.person@example.com"},
]

[project.scripts]
nn_verification_visualisation = "nn_verification_visualisation.main:main"